/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyIdRouteImport } from './routes/journey.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as JourneyIdPersonaliseRouteImport } from './routes/journey.$id.personalise'
import { Route as JourneyIdDetailsRouteImport } from './routes/journey.$id.details'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIdRoute = JourneyIdRouteImport.update({
  id: '/journey/$id',
  path: '/journey/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const JourneyIdPersonaliseRoute = JourneyIdPersonaliseRouteImport.update({
  id: '/personalise',
  path: '/personalise',
  getParentRoute: () => JourneyIdRoute,
} as any)
const JourneyIdDetailsRoute = JourneyIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => JourneyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/loading': typeof LoadingRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/journey/$id/details': typeof JourneyIdDetailsRoute
  '/journey/$id/personalise': typeof JourneyIdPersonaliseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/loading': typeof LoadingRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/journey/$id/details': typeof JourneyIdDetailsRoute
  '/journey/$id/personalise': typeof JourneyIdPersonaliseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/loading': typeof LoadingRoute
  '/onboarding': typeof OnboardingRoute
  '/results': typeof ResultsRoute
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/journey/$id': typeof JourneyIdRouteWithChildren
  '/journey/$id/details': typeof JourneyIdDetailsRoute
  '/journey/$id/personalise': typeof JourneyIdPersonaliseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/loading'
    | '/onboarding'
    | '/results'
    | '/complete-profile'
    | '/dashboard'
    | '/api/chat'
    | '/journey/$id'
    | '/journey/$id/details'
    | '/journey/$id/personalise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/loading'
    | '/onboarding'
    | '/results'
    | '/complete-profile'
    | '/dashboard'
    | '/api/chat'
    | '/journey/$id'
    | '/journey/$id/details'
    | '/journey/$id/personalise'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/loading'
    | '/onboarding'
    | '/results'
    | '/_authenticated/complete-profile'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/journey/$id'
    | '/journey/$id/details'
    | '/journey/$id/personalise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoadingRoute: typeof LoadingRoute
  OnboardingRoute: typeof OnboardingRoute
  ResultsRoute: typeof ResultsRoute
  ApiChatRoute: typeof ApiChatRoute
  JourneyIdRoute: typeof JourneyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$id': {
      id: '/journey/$id'
      path: '/journey/$id'
      fullPath: '/journey/$id'
      preLoaderRoute: typeof JourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/journey/$id/personalise': {
      id: '/journey/$id/personalise'
      path: '/personalise'
      fullPath: '/journey/$id/personalise'
      preLoaderRoute: typeof JourneyIdPersonaliseRouteImport
      parentRoute: typeof JourneyIdRoute
    }
    '/journey/$id/details': {
      id: '/journey/$id/details'
      path: '/details'
      fullPath: '/journey/$id/details'
      preLoaderRoute: typeof JourneyIdDetailsRouteImport
      parentRoute: typeof JourneyIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface JourneyIdRouteChildren {
  JourneyIdDetailsRoute: typeof JourneyIdDetailsRoute
  JourneyIdPersonaliseRoute: typeof JourneyIdPersonaliseRoute
}

const JourneyIdRouteChildren: JourneyIdRouteChildren = {
  JourneyIdDetailsRoute: JourneyIdDetailsRoute,
  JourneyIdPersonaliseRoute: JourneyIdPersonaliseRoute,
}

const JourneyIdRouteWithChildren = JourneyIdRoute._addFileChildren(
  JourneyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LoadingRoute: LoadingRoute,
  OnboardingRoute: OnboardingRoute,
  ResultsRoute: ResultsRoute,
  ApiChatRoute: ApiChatRoute,
  JourneyIdRoute: JourneyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
